version: '2.3'
services:
  splt:
    image:  gcr.io/kaggle-gpu-images/python:v85
    tty: true # シェルを実行できるようにする（開発環境用）。
    ports:
      - "18892:8888" # 外部ポート:内部ポート　：　ポートフォワーディング
    volumes: # フォルダのマウント
      - .:/root/workspace
    working_dir: /root/workspace # カレントディレクトリの指定
    command: bash -c "jupyter notebook --notebook-dir='/root/workspace' --ip=* --port 8888 --no-browser --allow-root --NotebookApp.password='sha1:ff3add95302a:5d2ae03d1ec9ace4f7865aa2f3985b3e6447d740'"
